// =====================================================================
//  selections.js — generated by picker.html
//
//  Per-project image overrides. If a slug has entries here, the detail
//  page shows EXACTLY those images (in that order). If a slug is omitted
//  or its array is empty, the detail page automatically shows every
//  uploaded custom image followed by every PDF page render of that
//  project's report.
//
//  Default = all PDF pages. Use the picker to curate a shorter set if
//  you want a particular project's gallery trimmed.
// =====================================================================
window.SELECTIONS = {};
