// =====================================================================
//  selections.js — generated by picker.html
//
//  Two records per editing session:
//
//    window.SELECTIONS  — per-project images shown in the sidebar
//                         "Selected figures" mini-gallery on the
//                         project detail page.
//
//    window.COVERS      — per-project cover image used on the home
//                         page card. If not set, the home falls back
//                         to the first selection / first upload /
//                         first figure / first page render.
//
//  Edit via picker.html (⭐ button to set cover, click tile to add to
//  Selected figures), then ⬇ Download or ⬆ Push.
// =====================================================================
window.SELECTIONS = {
  "spherical-graduation": [
    "custom/spherical-graduation/262c8b5e-a084-4263-9cfe-803af2c95762-motoci7b.jpg",
    "custom/spherical-graduation/2372c52c-2cf7-4d57-bb87-738ef39d2c1b-motodb81.jpg",
    "custom/spherical-graduation/panel-tracker_pi2-1-motofuz4.png",
    "custom/spherical-graduation/image-motpjyzi.png",
    "custom/spherical-graduation/Ekran-g-r-nt-s-2026-05-06-100242-motpn6dk.png"
  ],
  "drone-swarm": [
    "custom/drone-swarm/formation_edited_v2-moto81yo.gif",
    "custom/drone-swarm/formation_editedgif-moto8503.gif",
    "custom/drone-swarm/obs_avoid_attack-moto88ib.gif",
    "custom/drone-swarm/drone-swarm-scaled-moto8hjb.jpg",
    "custom/drone-swarm/perdixswarm-moto8qc6.gif"
  ],
  "celeba-vgg16": [
    "custom/celeba-vgg16/Ekran-g-r-nt-s-2026-05-06-100420-motppum2.png"
  ],
  "me408-control": [
    "custom/me408-control/Ekran-g-r-nt-s-2026-05-06-100722-motpt8ed.png",
    "custom/me408-control/Ekran-g-r-nt-s-2026-05-06-100929-motpwnfr.png",
    "custom/me408-control/Ekran-g-r-nt-s-2026-05-06-100837-motpwp2q.png"
  ],
  "quadrotor": [
    "custom/quadrotor/Ekran-g-r-nt-s-2026-05-06-101459-motq3dod.png",
    "custom/quadrotor/Ekran-g-r-nt-s-2026-05-06-101405-motq3f94.png",
    "custom/quadrotor/Ekran-g-r-nt-s-2026-05-06-101550-motq4kh8.png"
  ],
  "ev3-odometry": [
    "custom/ev3-odometry/Ekran-g-r-nt-s-2026-05-06-102059-motqbzgl.png",
    "custom/ev3-odometry/Ekran-g-r-nt-s-2026-05-06-102138-motqc185.png"
  ],
  "me308-lab5": [
    "custom/me308-lab5/Ekran-g-r-nt-s-2026-05-06-102304-motqe9u0.png",
    "custom/me308-lab5/Ekran-g-r-nt-s-2026-05-06-102304-motqejc6.png"
  ],
  "me308-lab7": [
    "custom/me308-lab7/Ekran-g-r-nt-s-2026-05-06-102827-motqkzk1.png"
  ]
};

window.COVERS = {
  // Set via picker (⭐). Examples:
  // "drone-swarm": "custom/drone-swarm/drone-swarm-scaled-moto8hjb.jpg",
};
